version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    container_name: spring-app
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: ecommerce_user
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect

      MY_CLOUDINARY_URL: cloudinary://637996999391574:HWDHqaYL2GZFnZhcDBhy9IZH758@dhyjrmavt
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
